### ISSUE TITLE
[Bugfix] CI-CD 워크플로 오류 발생

### ISSUE THREAD

**Issue by developbeginner** [developbeginner/project-easy-community#4]
### Description
`main` 브랜치에 pull request를 시도했으나, CI-CD 워크플로가 작동하지 않으며 startup failure가 발생했습니다.

오류코드는 아래와 같이 확인됩니다.
```
[Invalid workflow file: .github/workflows/ci-cd.yml#L65](https://github.com/developbeginner/project-easy-community/actions/runs/6728123267/workflow)
The workflow is not valid. .github/workflows/ci-cd.yml (Line: 65, Col: 14): Unexpected symbol: 'PROJECT/NAME'. Located at position 5 within expression: env.PROJECT/NAME
```

**Comment by developbeginner** [comment]
### Description
'PROJECT/NAME'을 'PROJECT_NAME'으로 오타를 수정했으나, 여전히 작동하지 않으며 새로운 오류코드가 발생되었습니다.

오류코드는 아래와 같이 확인됩니다.
```
[Invalid workflow file: .github/workflows/ci-cd.yml#L60](https://github.com/developbeginner/project-easy-community/actions/runs/6728880210/workflow)
The workflow is not valid. .github/workflows/ci-cd.yml (Line: 60, Col: 12): Job 'docker-pull' depends on unknown job 'docker'.
```

**Comment by developbeginner** [comment]
### Description
`build` 작업은 성공했습니다. 그러나 `docker-push` 작업 중 중단되며 새로운 오류코드가 발생되었습니다.

오류코드는 아래와 같이 확인됩니다.
```
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3202134687/Dockerfile: no such file or directory
```

**Comment by developbeginner** [comment]
### Resolves

#### [첫 번째 오류](https://github.com/developbeginner/project-easy-community/issues/4#issue-1973561568)
```
[Invalid workflow file: .github/workflows/ci-cd.yml#L65](https://github.com/developbeginner/project-easy-community/actions/runs/6728123267/workflow)
The workflow is not valid. .github/workflows/ci-cd.yml (Line: 65, Col: 14): Unexpected symbol: 'PROJECT/NAME'. Located at position 5 within expression: env.PROJECT/NAME
```
환경변수로 선언한 변수명이 `PROJECT_NAME`이 아닌 `PROJECT/NAME`으로 되어있었습니다. 이름을 변경하여 해결했습니다.

#### [두 번째 오류](https://github.com/developbeginner/project-easy-community/issues/4#issuecomment-1790122108)
```
[Invalid workflow file: .github/workflows/ci-cd.yml#L60](https://github.com/developbeginner/project-easy-community/actions/runs/6728880210/workflow)
The workflow is not valid. .github/workflows/ci-cd.yml (Line: 60, Col: 12): Job 'docker-pull' depends on unknown job 'docker'.
```
`docker-pull`의 needs에 잘못된 job이 할당되어 있었습니다. 마찬가지로 이름을 변경하여 해결했습니다.

#### [DockerFile 인식 오류](https://github.com/developbeginner/project-easy-community/issues/4#issuecomment-1790155593)
```
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3202134687/Dockerfile: no such file or directory
```
`build`와 `docker-push`의 환경이 일치하지 않아서 `DockerFile`을 인식할 수 없었습니다. 오류를 일으킨 `docker-push`를 `build`에 병합하여 해결했습니다.

#### Runner 오류
```
runner/run.sh’ already exists.
at System.IO.FileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
```
코드에서 발생한 오류가 아니라 별도의 이슈를 생성하지 않았으나, `deploy` 에서 작업이 계속 실패하여 모든 레포지토리의 Runner를 제거하고 재설치하여 해결했습니다.

### Reference
- [Run.sh already exists when running workflow](https://github.com/orgs/community/discussions/25263)
